config/routes.rb
Rails.application.routes.draw do
  root 'zines#display'
  
  get '/zines', to: 'zines#display'  
  get '/mission', to: 'static_pages#mission'
  get '/team', to: 'static_pages#team'
  get '/project', to: 'static_pages#project'
  get '/glossary', to: 'static_pages#glossary'
  get '/resources', to: 'static_pages#resources'
  get '/joinus', to: 'static_pages#joinus'
  get '/blog', to: 'blogs#show' 
   
  resources :blogs
  resources :zines
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/models/blogpost.rb
class Blogpost < ApplicationRecord
end

app/models/qsefile.rb
class Qsefile < ApplicationRecord
end

app/models/zine.rb
class Zine < ApplicationRecord
  has_one_attached :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[ show edit update destroy ]

  # GET /blogs or /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1 or /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs or /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to blog_url(@blog), notice: "Blog was successfully created." }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1 or /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to blog_url(@blog), notice: "Blog was successfully updated." }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1 or /blogs/1.json
  def destroy
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to blogs_url, notice: "Blog was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:title, :author, :content, :tags, :category)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def glossary
  end

  def project
  end

  def mission
  end

  def team
  end

  def resources
  end
end

app/controllers/zines_controller.rb
class ZinesController < ApplicationController
  before_action :set_zine, only: %i[ show edit update destroy ]

  # GET /zines or /zines.json
  def index
    @zines = Zine.all
  end
  
  def display
    @zines = Zine.all
  end

  # GET /zines/1 or /zines/1.json
  def show
  end

  # GET /zines/new
  def new
    @zine = Zine.new
  end

  # GET /zines/1/edit
  def edit
  end

  # POST /zines or /zines.json
  def create
    @zine = Zine.new(zine_params)

    respond_to do |format|
      if @zine.save
        format.html { redirect_to zine_url(@zine), notice: "Zine was successfully created." }
        format.json { render :show, status: :created, location: @zine }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @zine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /zines/1 or /zines/1.json
  def update
    respond_to do |format|
      if @zine.update(zine_params)
        format.html { redirect_to zine_url(@zine), notice: "Zine was successfully updated." }
        format.json { render :show, status: :ok, location: @zine }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @zine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /zines/1 or /zines/1.json
  def destroy
    @zine.destroy

    respond_to do |format|
      format.html { redirect_to zines_url, notice: "Zine was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_zine
      @zine = Zine.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def zine_params
      params.require(:zine).permit(:title, :description, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full name of the page on a per-pages basis
  def full_title(page_title = '')
    base_title = "Queer Sex Ed CC"
    if page_title.empty?
      base_title
    else
      page_title + ' | ' + base_title
    end
  end

end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/zines_helper.rb
module ZinesHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
        <% blog.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :tags %>
    <%= form.text_field :tags %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Content</th>
      <th>Tags</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= blog.author %></td>
        <td><%= blog.content %></td>
        <td><%= blog.tags %></td>
        <td><%= blog.category %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @blog.author %>
</p>

<p>
  <strong>Content:</strong>
  <%= @blog.content %>
</p>

<p>
  <strong>Tags:</strong>
  <%= @blog.tags %>
</p>

<p>
  <strong>Category:</strong>
  <%= @blog.category %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    © Copyright 2022 TLW Solutions
  </small>

  <nav>
    <ul> 
        <a href = "https://facebook.com/Queer-Sex-Ed-Community-Curriculum-111380534077841"  class = "fa fa-facebook" target = "_blank"></a>
        <a href = "https://twitter.com/QueerSexEdCC" class = "fa fa-twitter" target = "_blank" ></a>
        <a href = "https://instagram.com/queersexedcc" class = "fa fa-instagram" target = "_blank" ></a>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header> 
  <div class = "container">
    <div class = "row">
      <div class = "col-md-7">
          <%= link_to "Queer Sex Ed Curriculum", root_path, id: "logo" %>
      </div>

      <div class = "col-md-2">
        <a href = "https://facebook.com/Queer-Sex-Ed-Community-Curriculum-111380534077841"  class = "fa fa-facebook" target = "_blank"></a>
        <a href = "https://twitter.com/QueerSexEdCC" class = "fa fa-twitter" target = "_blank" ></a>
        <a href = "https://instagram.com/queersexedcc" class = "fa fa-instagram" target = "_blank" ></a>
      </div>    
      
      <div class = "col-md-3">
          <%= image_tag("logo.png", :alt => "logo") %>
      </div>
     </div>

      <div class = "row "> 
         <div class = "col-md-4">
         </div>
         <div class = "col-md-8 mx-auto">
         <nav class = "navbar">
           <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed"
                                    data-toggle="collapse"
                                    data-target="#bs-example-navbar-collapse-1"
                                    aria-expanded="false"
                                   >
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          </div>
    
          <ul class = "nav navbar-nav collapse navbar-collapse"
                      id="bs-example-navbar-collapse-1">
            <li><%= link_to "Blog", blogs_path %></li>
            <li><%= link_to "Zines", zines_path %></li>
          
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                About <b class = "caret"></b>
              </a>
            
              <ul class="dropdown-menu">
                <li><%= link_to "The Project", project_path %></li>
                <li><%= link_to "The Mission", mission_path %></li>
                <li><%= link_to "The Team", team_path %></li>
              </ul>
            </li>
          
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Curriculum <b class = "caret"></b>
              </a>

              <ul class="dropdown-menu">
                <li> <%= link_to "Curriculum", "#" %></li>
                <li> <%= link_to "Posters", "#" %></li>
              </ul>
            </li>

            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Community <b class = "caret"></b>
              </a>

              <ul class="dropdown-menu"> 
                <li> <%= link_to "Glossary", glossary_path %></li>
                <li> <%= link_to "Resources", resources_path %></li>
                <li> <%= link_to "Want to join us?", joinus_path %></li>
              </ul>
            </li>
          </ul>

        </nav>
        </div>
    </div>
  </div>
</header>

app/views/layouts/_mission.html.erb
<div class = "row text-center">
  <div class = "col">
    <h2>The Queer Sex Ed Community Curriculum is a free sexual and relational health curriculum for young people and adults. </h2>
    <%= image_tag("flag.jpg", alt: "multiple strings of pride flags shown blowing in the wind, connected to a brick building during sunset.") %>
  </div>
</div>

<div class = "row">
  <div class = "col">
    <h1>OUR MISSION</h1>
    <ul>
      <li>
        <p>QSECC strives to create a <b>pleasure-centered, trauma-informed, queer-inclusive</b>, and <b>socially</b> conscious curriculum.</p>
      </li>
      <li>
        <p>QSECC is an expansive platform that is committed to <b>reimagining the ways that knowledge is created, collected, and validated.</b> To that extent, we aspire to be an <b>open-source archive</b> of knowledge that stems from <b>many voices and perspectivesi</b></p>
      </li>
      <li>
        <p>QSECC attempts to <b>disrupt the established hierarchy</b> of validation of knowledge by purposefully uplifting the voices and knowledge of those who may not have access to <b>institutions of higher education, degrees, years of experience</b>, the <b>body</b>, or the <b>background</b> typically endowed with <b>epistemic authority</b> (or the power to create truths).</p>
      </li>
    </ul>
  </div>
</div>

app/views/layouts/_navbar.html.erb
         <nav> 
           <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed"
                                    data-toggle="collapse"
                                    data-target="#bs-example-navbar-collapse-1"
                                    aria-expanded="false"
                                   >
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          </div>
    
          <ul class = "nav navbar-nav navbar-right collapse navbar-collapse"
                      id="bs-example-navbar-collapse-1">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <% if logged_in? %>
             <li><%= link_to "Users", "#" %> </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                 Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", "#" %> </li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Log out", logout_path, method: :delete %>
                </li>
              </ul>
            </li>
          <% else %>
              <li><%= link_to "Log in", login_path %></li>
          <% end %>
          </ul>
        </nav>

app/views/layouts/_patreon.html.erb
<div class = "row text-center">
  <div class = "col">
    <h1>FIND US ON PATREON</h1>
    <div class = "row">
      <p>This project will <b>always be free</b> to access and be a part of - that’s a commitment we made at the beginning of this that we’re dedicated to. </p>
    </div>
    <div class = "row">
      <p>We launched a Patreon not to add a paywall to our content but instead to <b>ensure the sustainability of this project</b>, to support us as we balance creating these <b>free educational materials</b> with full-time jobs and general life pressures. </p>
    </div>
  </div>
  <div class = "row">
    <p>If you appreciate <b>the work we do</b> and are able to, please consider supporting us on Patreon from as low as $3 a month. <i>All patrons have access to the same perks (regardless of how much you are able to pay) - early access to virtual trainings, zine suggestions, and more.</i> </p> 
  </div>
  <a href = "https://www.patreon.com/queersexedcc" style = "border: 1px solid;">SUPPORT US ON PATREON!</a>
</div>

app/views/layouts/_readings.html.erb
<div class = "row">
    <div class = "col-md-6">
      <h3><a href = "https://www.youtube.com/c/TheSexTalkWebSeriesX/featured">The Sex Talk with Mou</a></h3>
    </div>
    <div class = "col-md-6">
      <p>Moushumi Ghose is a sex therapist  and author who hosts a YouTube channel dedicated to exploring and understanding sexual and mental health, and the intersections there. She has over 180 videos!</p>
    </div>
</div>

<div class = "row">
  <h1>READINGS</h1>
  <div class = "col-md-6">
    <h3><a href = "#">Pleasure Activism </a></h3>
  </div>
  <div class = "col-md-6">
    <p><i>Pleasure Activism: the Politics of Feeling Good</i> by adrienne maree brown is an accessible introduction to many aspects of sex positive thinking, such as queer theory, intersectionality, and the concept of pleasure activism.  </p>
  </div>
</div>

<div class = "row">
  <div class = "col-md-6">
    <h3><a href = "http://yanatallonhicks.com/blog/">The Sex Column</a></h3>
  </div>
  <div class = "col-md-6">
    <p>The Sex Column, by therapist and author Yanna Tallon-Hicks, is an on-going blog filled with  constantly updated information, including articles on how to have safe sex during the time of COVID-19. </p>
  </div>

<div class = "row">
  <div class = "col-md-6">
    <h3><a href = "https://www.beheroes.net/the-pride-guide">The Pride Guide</a></h3>
  </div>
  <div class = "col-md-6">
    <p>The Pride Guide: a Guide to Social and Sexual Health for LGBTQ Youth by Jo Langford is an excellent gender-expansive, trans-inclusive guide for kids and young adults who are navigating life through ever-changing bodies and minds. </p>
    </div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/_team.html.erb
<div class="row text-center mt-md-5 center">
    <div class="col-md-6 col-12 mb-5 ">
      <%= image_tag("heather.jpg", class: "img-fluid rounded-circle mt-3 mb-4 shadow")%>
      <h3><strong>Heather Welty</strong> <a href="https://www.linkedin.com" 
                                          class="fa fa-linkedin" target="_blank"></a></h3>
      <p><strong>Director, founder</strong> | <i>they/she</i></p>
      <p> Heather's interest in sex education and relational well-being centers around incorporating critical social theory into the pedagogy of public health education and therapy. She holds a B.A. in cognitive psychology and critical social theory and has a history in both lab and field research focusing on cognition, social psychology, and critical pedagogy. Heather is currently based in Western Massachusetts where they work supporting young people experiencing homelessness. </p>
    </div>
    

    <div class="col-md-6 col-12 mb-5">
      <%= image_tag("aly.jpg", class: "img-fluid rounded-circle mt-3 mb-4 shadow") %>
      <h3><strong>Aly Albertson</strong> <a href="https://linkedin.com" class = "fa fa-linkedin" target="_blank"></a></h3>
      <p><strong>Director, founder</strong> | <i>they/she</i> </p>
      <p>Al/Alb/Aly is a pleasure-based sexuality educator and researcher based in Amsterdam. They hold a Master of Science in Sociology: Gender, Sexuality, and Society, and a B.A. in sexuality education, gender/identity studies, and sexual health. They have worked at several international nongovernmental organizations as a researcher on pleasure focused sexual and reproductive health and rights initiatives. Their work focuses on intersections of power, health, knowledge, identity, pleasure, and educational pedagogy.</p>
    </div>
</div>

app/views/layouts/_virtual_resources.html.erb
 <div class = "row">
    <h1>VIRTUAL RESOURCES</h1>
    <div class = "col-md-6">
      <h3><a href = "https://futureofsexed.org/">Future Of Sex Education (FoSe)</a></h3>
    </div>
    <div class = "col-md-6">
      <p>FoSe is  an incredible database of information for all things sex education. They offer research, professional development, curriculum, and implementation practices. </p>
    </div>
 </div>

 <div class = "row">
    <div class = "col-md-6">
      <h3><a href= "https://www.onlinetherapy.com/resources-for-lgbtq/">LGBTQ+ Mental Health</h3></a>
    </div>
    <div class = "col-md-6">
      <p>This guide covers some of the unique challenges faced by LGBTQ+ individuals, how therapy can help, tips for finding the right provider, and additional helpful resources. </p>
    </div>
</div>

<div class = "row">
    <div class = "col-md-6">
      <h3><a href = "https://www.queersexed.org/">Queer Sex Ed</a></h3>
    </div>
    <div class = "col-md-6">
      <p>QueerSexEd.org is a podcast and training organization. They offer webinars and in-person trainings, as well as an archive and transcripts of all of their podcasts.</p>
    </div>
</div>

<div class = "row">
    <div class = "col-md-6">
      <h3><a href = "https://www.scarleteen.com/"</h3></a>
    </div>
    <div class = "col-md-6">
      <p>Scarleteen is an organization that has been operating for over 20 years, offering services for teens and young adults such as advice, referrals, as well as sexual health content and podcasts.</p>
    </div>
</div>

app/views/layouts/_webinars_and_videos.html.erb
<div class = "row">
  <h1>WEBINARS AND VIDEOS</h1>

  <div class = "row">
    <div class = "col-md-6">
      <h3><a href = "vimeo.com/306867344">GLSEN's Sex Ed Webinar</a></h3>
    </div>
    <div class = "col-md-6">
      <p>This 30 minute webinar, produced by GLSEN, covers topics related to LGBTQIA+ sex education for students.</p>
    </div>
  </div>

  <div class = "row">
    <div class = "col-md-6">
      <h3><a href = "http://www.sbh4all.org/events/making-room-for-gender-diversity-in-school-health-services-and-sex-education/">Gender Diversity in Sex Ed</a></h3>
    </div>
    <div class = "col-md-6">
      <p>This 1 hour webinar, produced by GLSEN, explores research, pedagogical approaches, and affirming practices for creating inclusive sex ed classes in schools.</p>
    </div>
  </div>

  <div class = "row">
    <div class = "col-md-6">
      <h3><a href = "https://exploresextalk.com/">UCLA Continuing Education </a></h3>
    </div>
    <div class = "col-md-6">
      <p>This extensive database of webinars, curated by the YMSM+LGBT group at UCLA, offers information on a multitude of topics from transgender healthcare to HIV+ awareness and testing. There are about 20 webinars in this database, each about 1 hour long. </p>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %> </title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, inital-scale=1"> 
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class = "container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/static_pages/mission.html.erb
<% provide(:title, "THE MISSION") %>

<h1><%= yield(:title) %></h1>
<%= render 'layouts/mission' %>
<%= render 'layouts/patreon' %>

app/views/static_pages/project.html.erb
<% provide(:title, "THE PROJECT") %>

<div class = "row">
  <div class = "col">
    <h1><%= yield(:title) %></h1>
    <ul>
      <li>
        <p>Queer Sex Ed Community Curriculum was created out of the need for a sexual health curriculum that is: <b>accessible</b>, <b>accurate</b>, and </b>accountable</b>. </p></li>
      <li>
        <p>We believe that everyone has a right to access and take part in building a curriculum that centers on <b>consent</b>, <b>pleasure</b>, and <b>authenticity</b>.</p>
      </li>
    </ul>
  </div>
</div>

<div class = "row " style = "border: 1px solid white;">
  
  <div class = "col-md-6">
  <%= image_tag("window.jpg", size: "412x309", alt: "A window sill with a monstera plant, assorted mugs, and zines. A sidewalk and bicycle can be seen outside.") %>
  </div>

  <div class = "col-md-6">
    <div class = "row">
      <h2>01.<br>EDUCATE</h2>
    </div>
    <div class = "row">
      <p>We create educational <b>zines, posters, curriculum</b>, and <b>articles.</b></p>
    </div>
    <div class = "row">
      <h3>EVERYTHING WE CREATE IS FREE TO DOWNLOAD.</h3>
    </div>
    <div class = "row">
      <p><i>We plan to offer both virtual and in-person training soon.</i></p>
    </div>
    <div class = "row">
      <%= link_to "VIEW OUR ZINE ARCHIVE", "#" %>
    </div>
  </div>
</div>



<div class = "row" style = "border: 1px solid white;">
  <div class = "col-md-6">
    <div class = "row">
      <h2>02.<br>DISRUPT</h2>
    </div>
    <div class = "row">
      <p>We disrupt the traditional hierarchy of knowledge by <b>validating</b> and <b>publishing</b> the perspectives of anyone within our community</p>
    </div>
    <div class = "row">
      <h3>YOU CAN JOIN US IN CREATING THIS CURRICULUM</h3>
    </div>
    <div class = "row">
      <%= link_to "VIEW OUR MISSION", '#' %>
    </div>
  </div>
  <div class = "col-md-6">
    <%= image_tag("bookshelf.jpg", alt: "A multilayered bookshelf with many different colored books.") %>
  </div>
</div>

<div class = "row" style = "border: 1px solid white;">
  <div class = "col-md-6">
    <%= image_tag("whiteboard.jpg", alt: "Two hands holding markers designing a website together on a white board.") %>
  </div>
  <div class = "col-md-6">
    <div class = "row">
      <h2>03.<br>COLLABORATE</h2>
    </div>
    <div class = "row">
      <p>This project would not exist without collaboration</p>
    </div>
    <div class = "row">
      <h2>A community curriculum depends on the community.</h2>
    </div>
    <div class = "row">
      <p>(That means you!)</p>
    </div>
    <div class = "row">
      <%= link_to "REACH OUT TO US!", '#' %>
    </div>

  </div>


</div>

app/views/static_pages/resources.html.erb
<% provide(:title, "RESOURCES") %>
<%= render 'layouts/virtual_resources' %>
<%= render 'layouts/webinars_and_videos' %>
<%= render 'layouts/readings.html.erb' %>

app/views/static_pages/team.html.erb
<% provide(:title, "THE TEAM") %>

<h1><u><%= yield(:title) %></u></h1>
<%= render 'layouts/team' %>

app/views/zines/_form.html.erb
<%= form_with(model: zine) do |form| %>
  <% if zine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(zine.errors.count, "error") %> prohibited this zine from being saved:</h2>

      <ul>
        <% zine.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  
  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/zines/edit.html.erb
<h1>Editing Zine</h1>

<%= render 'form', zine: @zine %>

<%= link_to 'Show', @zine %> |
<%= link_to 'Back', zines_path %>

app/views/zines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Zines</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @zines.each do |zine| %>
      <tr>
        <td><%= zine.title %></td>
        <td><%= zine.description %></td>
        <td><%= link_to 'Show', zine %></td>
        <td><%= link_to 'Edit', edit_zine_path(zine) %></td>
        <td><%= link_to 'Destroy', zine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Zine', new_zine_path %>

app/views/zines/new.html.erb
<h1>New Zine</h1>

<%= render 'form', zine: @zine %>

<%= link_to 'Back', zines_path %>

app/views/zines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @zine.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @zine.description %>
</p>

<p>
    <strong>Uploaded File</strong>
      <% if @zine.image.image? %>
        <%= image_tag(@zine.image) %>
      <% else %>
        <% if @zine.image.previewable? %>
          <%= image_tag @zine.image.preview(resize_to_limit: [100, 100]) %>
        <% end %>
        <%= link_to @zine.image.filename, rails_blob_path(@zine.image, disposition: "attachment") %>
      <% end %>
</p>

<%= link_to 'Edit', edit_zine_path(@zine) %> |
<%= link_to 'Back', zines_path %>